import { GAMING } from '@/rbac/permissions'
import type { RouteDefinition } from '@/rbac/types'
import { defineRoute, gamingRoute } from './helpers'

export const gamingRoutes: RouteDefinition[] = [
  defineRoute(
    'GET',
    '/business-units/:businessUnitId/gaming-house/customers',
    gamingRoute(GAMING.READ),
  ),
  defineRoute(
    'POST',
    '/business-units/:businessUnitId/gaming-house/customers',
    gamingRoute(GAMING.CREATE),
  ),
  defineRoute(
    'PATCH',
    '/business-units/:businessUnitId/gaming-house/customers/:id',
    gamingRoute(GAMING.UPDATE),
  ),
  defineRoute(
    'DELETE',
    '/business-units/:businessUnitId/gaming-house/customers/:id',
    gamingRoute(GAMING.DELETE),
  ),
  defineRoute(
    'GET',
    '/business-units/:businessUnitId/gaming-house/consoles',
    gamingRoute(GAMING.READ),
  ),
  defineRoute(
    'POST',
    '/business-units/:businessUnitId/gaming-house/consoles',
    gamingRoute(GAMING.CREATE),
  ),
  defineRoute(
    'PATCH',
    '/business-units/:businessUnitId/gaming-house/consoles/:id',
    gamingRoute(GAMING.UPDATE),
  ),
  defineRoute(
    'DELETE',
    '/business-units/:businessUnitId/gaming-house/consoles/:id',
    gamingRoute(GAMING.DELETE),
  ),
  defineRoute(
    'GET',
    '/business-units/:businessUnitId/gaming-house/games',
    gamingRoute(GAMING.READ),
  ),
  defineRoute(
    'POST',
    '/business-units/:businessUnitId/gaming-house/games',
    gamingRoute(GAMING.CREATE),
  ),
  defineRoute(
    'PATCH',
    '/business-units/:businessUnitId/gaming-house/games/:id',
    gamingRoute(GAMING.UPDATE),
  ),
  defineRoute(
    'DELETE',
    '/business-units/:businessUnitId/gaming-house/games/:id',
    gamingRoute(GAMING.DELETE),
  ),
  defineRoute(
    'POST',
    '/business-units/:businessUnitId/gaming-house/sessions/start',
    gamingRoute(GAMING.CREATE),
  ),
  defineRoute(
    'POST',
    '/gaming-house/sessions/:sessionId/end',
    gamingRoute(GAMING.CREATE),
  ),
  defineRoute(
    'GET',
    '/business-units/:businessUnitId/gaming-house/sessions',
    gamingRoute(GAMING.READ),
  ),
  defineRoute(
    'POST',
    '/gaming-house/sessions/:sessionId/payments',
    gamingRoute(GAMING.PAYMENTS_CREATE),
  ),
  defineRoute(
    'GET',
    '/gaming-house/sessions/:sessionId/payments',
    gamingRoute(GAMING.PAYMENTS_READ),
  ),
  defineRoute(
    'POST',
    '/business-units/:businessUnitId/gaming-house/expenses',
    gamingRoute(GAMING.CREATE),
  ),
  defineRoute(
    'GET',
    '/business-units/:businessUnitId/gaming-house/expenses',
    gamingRoute(GAMING.READ),
  ),
  defineRoute(
    'POST',
    '/business-units/:businessUnitId/gaming-house/tournaments',
    gamingRoute(GAMING.CREATE),
  ),
  defineRoute(
    'GET',
    '/business-units/:businessUnitId/gaming-house/tournaments',
    gamingRoute(GAMING.READ),
  ),
  defineRoute(
    'GET',
    '/business-units/:businessUnitId/gaming-house/reports/revenue',
    gamingRoute(GAMING.REPORTS_READ),
  ),
]
